
target 'IBety' do
use_frameworks!
pod 'DropDown'
pod 'Segmentio', '~> 3.3'
pod 'BATabBarController'
pod 'SSCustomTabbar'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage'
pod 'RadioGroup'
pod 'BSImagePicker', '~> 2.8'
pod 'IQKeyboardManager'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'FlagPhoneNumber'
end
